"""create documents and document chunks

Revision ID: 7f7483ec3680
Revises:
Create Date: 2026-09-24 18:43:27.273131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

# revision identifiers, used by Alembic.
revision: str = '7f7483ec3680'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'ready', 'failed')", name=op.f('ck_documents_valid_status')),
    sa.CheckConstraint('page_count > 0', name=op.f('ck_documents_positive_page_count')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents')),
    sa.UniqueConstraint('content_sha256', name=op.f('uq_documents_content_sha256'))
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('document_id', sa.Uuid(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_space', sa.String(length=128), nullable=False),
    sa.Column('embedding', VECTOR(384), nullable=False),
    sa.CheckConstraint("embedding_space = 'fastembed:bge-small-en-v1.5:384:l2:v1'", name=op.f('ck_document_chunks_supported_embedding_space')),
    sa.CheckConstraint('chunk_index >= 0', name=op.f('ck_document_chunks_nonnegative_index')),
    sa.CheckConstraint('length(btrim(content)) > 0', name=op.f('ck_document_chunks_nonempty_content')),
    sa.CheckConstraint('page_number >= 1', name=op.f('ck_document_chunks_positive_page')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_document_position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document_chunks')
    op.drop_table('documents')
    # ### end Alembic commands ###
